### PR TITLE
migrate favicons from app.decenterai.com

### LINKED ISSUE #46: chore: migrate favicons from app.decenterai.com
- [ ] take meta configuration from https://github.com/DeCenter-AI/app.decenterai.com/blob/main/src/app/layout.tsx#L17
- [ ] also copy the favicons, and related files from public folder
- [ ] check the favicons with vercel preview deployment url over here: https://realfavicongenerator.net/favicon_checker

Reference: https://realfavicongenerator.net/favicon_checker?protocol=http&site=app.decenterai.com

### PR DESCRIPTION
**Pull request by utkarsh-1602**
## Related Issue(s)

Fixes #46 
<br>
For #

## Proposed Changes

[//]: # '[List down the specific changes you have made in this pull request.]'

- [x]

## Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [ ] I have added suitable unit tests (if applicable).

## To-Do

- [ ]

### CODE REVIEW

**Comment by Nasfame** [comment]
@utkarsh-1602 it seems like something has gone wrong: https://realfavicongenerator.net/favicon_checker?protocol=https&site=decenterai-92nb29cz6-decenter-ai.vercel.app

**Comment by Nasfame** [comment]
fix it:

**Comment by Nasfame** [comment]
fix it: 
image

**Review by techyNonso — DISMISSED** [review]

**Review by Nasfame — CHANGES_REQUESTED** [review]
the favicon checker is failing, kindly fix it

**Comment by Nasfame** [comment]
Overrided by #48

**Pull request closed without merging**
